### PR TITLE
Great Places to eat in Alexandria, VA

### PR DESCRIPTION
**Pull request by JeffreyRRoss**
Do you know any others?

### CODE REVIEW

**Comment by rsnakamura** [comment]
@JeffreyRRoss Never been to Alexandria. Not sure about oysters.

**Comment by cloverturf** [comment]
@atcunningham have you been to Hank's? I enjoy oysters.

**Comment by cloverturf** [comment]
@JeffreyRRoss  :+1:

**Comment by atcunningham** [comment]
@JeffreyRRoss @cloverturf  Haven't been to Hanks. Not sure about oysters.

**Pull request merged**
